/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Albums: typeof import('./src/components/datalist/Albums.vue')['default']
    ButtonGroup: typeof import('./src/components/button/ButtonGroup.vue')['default']
    Carousel: typeof import('./src/components/carousel/Carousel.vue')['default']
    Comment: typeof import('./src/components/common/Comment.vue')['default']
    CommentDialog: typeof import('./src/components/common/CommentDialog.vue')['default']
    DecoratedButton: typeof import('./src/components/button/DecoratedButton.vue')['default']
    Drawer: typeof import('./src/components/drawer/Drawer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    MoreButton: typeof import('./src/components/button/MoreButton.vue')['default']
    MoreDropdown: typeof import('./src/components/button/MoreDropdown.vue')['default']
    Mv: typeof import('./src/components/datalist/Mv.vue')['default']
    NoSearch: typeof import('./src/components/common/NoSearch.vue')['default']
    OnlineBatch: typeof import('./src/components/batch/OnlineBatch.vue')['default']
    Pagination: typeof import('./src/components/pagination/Pagination.vue')['default']
    PlayAnimation: typeof import('./src/components/common/PlayAnimation.vue')['default']
    PlayButton: typeof import('./src/components/button/PlayButton.vue')['default']
    PlayList: typeof import('./src/components/datalist/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./src/components/button/SearchButton.vue')['default']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    Singer: typeof import('./src/components/datalist/Singer.vue')['default']
    SongList: typeof import('./src/components/table/SongList.vue')['default']
    SortButton: typeof import('./src/components/button/SortButton.vue')['default']
    Tab: typeof import('./src/components/tab/Tab.vue')['default']
    UserBatch: typeof import('./src/components/batch/UserBatch.vue')['default']
    UserSongTable: typeof import('./src/components/table/UserSongTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
