/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArtistAlbum: typeof import('./src/components/datalist/artist-album/index.vue')['default']
    ArtistMv: typeof import('./src/components/datalist/artist-mv/index.vue')['default']
    ArtistPlaylist: typeof import('./src/components/datalist/artist-playlist/index.vue')['default']
    Aside: typeof import('./src/components/layout/aside/index.vue')['default']
    ButtonGroup: typeof import('./src/components/button/button-group/index.vue')['default']
    Carousel: typeof import('./src/components/carousel/index.vue')['default']
    ColorPicker: typeof import('./src/components/button/color-picker/index.vue')['default']
    Comment: typeof import('./src/components/common/comment/index.vue')['default']
    CommentDialog: typeof import('./src/components/common/CommentDialog.vue')['default']
    CommonButton: typeof import('./src/components/button/common-button/index.vue')['default']
    Drawer: typeof import('./src/components/drawer/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/footer/index.vue')['default']
    Header: typeof import('./src/components/layout/header/index.vue')['default']
    Loading: typeof import('./src/components/result/loading/index.vue')['default']
    Modal: typeof import('./src/components/common/modal/index.vue')['default']
    MoreButton: typeof import('./src/components/button/more-button/index.vue')['default']
    MoreDropdown: typeof import('./src/components/button/more-dropdown/index.vue')['default']
    NoResult: typeof import('./src/components/result/no-result/index.vue')['default']
    NoSearch: typeof import('./src/components/common/NoSearch.vue')['default']
    OnlineBatch: typeof import('./src/components/batch/online-batch/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    PlayAnimation: typeof import('./src/components/common/play-animation/index.vue')['default']
    PlayButton: typeof import('./src/components/button/play-button/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./src/components/button/search-button/index.vue')['default']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    Singer: typeof import('./src/components/datalist/singer/index.vue')['default']
    SongTable: typeof import('./src/components/table/song-table/index.vue')['default']
    SortButton: typeof import('./src/components/button/sort-button/index.vue')['default']
    Tab: typeof import('./src/components/tab/index.vue')['default']
    UserBatch: typeof import('./src/components/batch/user-batch/index.vue')['default']
    UserMusicTable: typeof import('./src/components/table/user-music-table/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
